from turtle import Turtle, Screen
timmy = Turtle()
timmy.shape("turtle")
timmy.color("red")
timmy.forward(100)
timmy.back(100)
timmy.left(80)
timmy.forward(100)
timmy.right(60)
timmy.forward(100)
screen = Screen()
screen.exitonclick()
